### PR TITLE
fix type mismatch error for arm

### LINKED ISSUE #6: Port mseed crate to arm
This is a follow-up issue of https://github.com/damb/mseed/issues/5#issuecomment-1688650095.

### PR DESCRIPTION
**Pull request by BIBIN-EUGINE**
**Description**

Resolved the portable issues of mseed crate for arm target

**Testing**

Tested this changes with cross compliation for arm target and it complied successfully.

### CODE REVIEW

**Comment by BIBIN-EUGINE** [comment]
Hi @damb , This PR is ready for review. Thanks

**Comment by damb** [comment]
Great. Could you please fix the formatting, firstly. `cargo-fmt` is your friend. Thanks.

File: src/io.rs [hunk 1]
```diff
@@ -266,7 +266,7 @@ impl<W: Write> MSWriter<W> {
                 Some(record_handler::<W>),
                 (&mut self.writer) as *mut _ as *mut c_void,
                 max_rec_len,
-                encoding as c_char,
+                (encoding as c_char).try_into().unwrap(),
```
Comment (damb) [inline src/io.rs]: Casting and converting (i.e. basically casting twice) is not required. Instead, use

```rust
encoding as _
```

and let the compiler infer the destination type (see https://doc.rust-lang.org/std/keyword.as.html).

File: src/pack.rs [hunk 2]
```diff
@@ -68,15 +68,15 @@ where
...
+    let cnt_samples: c_long = 0;
+    let cnt_samples_ptr = &mut cnt_samples.into();
     let cnt_records = unsafe {
         check(raw::mstl3_pack(
             mstl.get_raw_mut(),
             Some(rh_wrapper::<F>),
             (&mut record_handler) as *mut _ as *mut c_void,
             info.rec_len,
-            info.encoding as c_char,
+            (info.encoding as c_char).try_into().unwrap(),
```
Comment (damb) [inline src/pack.rs]: See above.

```rust
info.encoding as _
```

is the way to go.

File: src/pack.rs [hunk 3]
```diff
@@ -289,7 +289,7 @@ where
     unsafe {
         let sid_len = info.sid().as_bytes_with_nul().len();
         ptr::copy_nonoverlapping(info.sid().as_ptr(), (*msr).sid.as_mut_ptr(), sid_len);
-        (*msr).encoding = info.encoding as c_char;
+        (*msr).encoding = (info.encoding as c_char).try_into().unwrap();
```
Comment (damb) [inline src/pack.rs]: See above. Casting twice not required.

File: src/record.rs [hunk 4]
```diff
@@ -32,7 +32,7 @@ pub fn detect<T: AsRef<[u8]>>(buf: T) -> MSResult<RecordDetection> {
     let rec_len = unsafe {
         check(raw::ms3_detect(
             buf.as_ptr() as *const _,
-            buf.len() as c_ulong,
+            (buf.len() as c_ulong).into(),
```
Comment (damb) [inline src/record.rs]: See above. Casting twice is not required.

File: src/pack.rs [hunk 5]
```diff
@@ -321,8 +322,8 @@ where
         }
     }
 
-    let mut cnt_samples: c_long = 0;
-    let cnt_samples_ptr = &mut cnt_samples as *mut _;
+    let cnt_samples: c_long = 0;
```
Comment (damb) [inline src/pack.rs]: See https://github.com/damb/mseed/pull/8#discussion_r1304279687.

File: src/pack.rs [hunk 6]
```diff
@@ -380,8 +381,8 @@ pub fn pack_record<F>(
 where
     F: FnMut(&[u8]),
 {
-    let mut cnt_samples: c_long = 0;
-    let cnt_samples_ptr = &mut cnt_samples as *mut _;
+    let cnt_samples: c_long = 0;
```
Comment (damb) [inline src/pack.rs]: See https://github.com/damb/mseed/pull/8#discussion_r1304279687.

File: src/record.rs [hunk 7]
```diff
@@ -213,7 +213,7 @@ impl MSRecord {
         if !self.ptr().datasamples.is_null() {
             return Ok(self.num_samples());
         }
-        unsafe { check(raw::msr3_unpack_data(self.0, 0)) }
+        unsafe { check(raw::msr3_unpack_data(self.0, 0).try_into().unwrap()) }
```
Comment (damb) [inline src/record.rs]: The code should do what it is expected to do. Though, I prefer the shorter

```rust
unsafe { check(raw::msr3_unpack_data(self.0, 0)) as _ } 
```

since it is less verbose and IMO more idiomatic.

File: src/record.rs [hunk 8]
```diff
@@ -278,12 +278,12 @@ impl MSRecord {
 
     /// Returns the start time of the record (i.e. the time of the first sample).
     pub fn start_time(&self) -> MSResult<time::OffsetDateTime> {
-        util::nstime_to_time(self.ptr().starttime)
+        util::nstime_to_time(self.ptr().starttime.try_into().unwrap())
```
Comment (damb) [inline src/record.rs]: See above. Cast with `as _` instead.

File: src/record.rs [hunk 9]
```diff
@@ -278,12 +278,12 @@ impl MSRecord {
...
     }
 
     /// Calculates the end time of the last sample in the record.
     pub fn end_time(&self) -> MSResult<time::OffsetDateTime> {
-        unsafe { util::nstime_to_time(check_nst(raw::msr3_endtime(self.0))?) }
+        unsafe { util::nstime_to_time(check_nst(raw::msr3_endtime(self.0).try_into().unwrap())?) }
```
Comment (damb) [inline src/record.rs]: Cast with `as _`.

File: src/record.rs [hunk 10]
```diff
@@ -303,7 +303,7 @@ impl MSRecord {
 
     /// Returns the number of data samples as indicated by the raw record.
     pub fn sample_cnt(&self) -> c_long {
-        self.ptr().samplecnt
+        self.ptr().samplecnt.try_into().unwrap()
```
Comment (damb) [inline src/record.rs]: Cast with `as _`.

File: src/record.rs [hunk 11]
```diff
@@ -352,17 +352,17 @@ impl MSRecord {
 
     /// Returns the number of (unpacked) data samples.
     pub fn num_samples(&self) -> c_long {
-        self.ptr().numsamples
+        self.ptr().numsamples.try_into().unwrap()
```
Comment (damb) [inline src/record.rs]: Cast with `as _`.

File: src/record.rs [hunk 12]
```diff
@@ -411,7 +411,7 @@ impl fmt::Display for MSRecord {
             v.samplecnt,
             self.sample_rate_hz(),
             util::nstime_to_string(
-                v.starttime,
+                v.starttime.try_into().unwrap(),
```
Comment (damb) [inline src/record.rs]: Cast with `as _`.

File: src/record.rs [hunk 13]
```diff
@@ -470,7 +470,7 @@ impl fmt::Display for RecordDisplay<'_> {
             )?;
             let start_time = unsafe { (*self.rec.get_raw()).starttime };
             let start_time = util::nstime_to_string(
-                start_time,
+                start_time.try_into().unwrap(),
```
Comment (damb) [inline src/record.rs]: Cast with `as _`.

File: src/trace.rs [hunk 14]
```diff
@@ -43,12 +43,12 @@ impl MSTraceId {
 
     /// Returns the time of the the first sample.
     pub fn start_time(&self) -> MSResult<OffsetDateTime> {
-        util::nstime_to_time(self.ptr().earliest)
+        util::nstime_to_time(self.ptr().earliest.try_into().unwrap())
```
Comment (damb) [inline src/trace.rs]: Cast with `as _`.

File: src/trace.rs [hunk 15]
```diff
@@ -43,12 +43,12 @@ impl MSTraceId {
...
     }
 
     /// Returns the time of the the last sample.
     pub fn end_time(&self) -> MSResult<OffsetDateTime> {
-        util::nstime_to_time(self.ptr().latest)
+        util::nstime_to_time(self.ptr().latest.try_into().unwrap())
```
Comment (damb) [inline src/trace.rs]: Cast with `as _`.

File: src/trace.rs [hunk 16]
```diff
@@ -106,12 +106,12 @@ impl<'id> MSTraceSegment<'id> {
 
     /// Returns the time of the the first sample.
     pub fn start_time(&self) -> MSResult<OffsetDateTime> {
-        util::nstime_to_time(self.ptr().starttime)
+        util::nstime_to_time(self.ptr().starttime.try_into().unwrap())
```
Comment (damb) [inline src/trace.rs]: Cast with `as _`.

File: src/trace.rs [hunk 17]
```diff
@@ -106,12 +106,12 @@ impl<'id> MSTraceSegment<'id> {
...
     }
 
     /// Returns the time of the the last sample.
     pub fn end_time(&self) -> MSResult<OffsetDateTime> {
-        util::nstime_to_time(self.ptr().endtime)
+        util::nstime_to_time(self.ptr().endtime.try_into().unwrap())
```
Comment (damb) [inline src/trace.rs]: Cast with `as _`.

File: src/trace.rs [hunk 18]
```diff
@@ -121,7 +121,7 @@ impl<'id> MSTraceSegment<'id> {
 
     /// Returns the number of samples in trace coverage.
     pub fn sample_cnt(&self) -> c_long {
-        self.ptr().samplecnt
+        self.ptr().samplecnt.try_into().unwrap()
```
Comment (damb) [inline src/trace.rs]: Cast with `as _`.

File: src/trace.rs [hunk 19]
```diff
@@ -151,12 +151,12 @@ impl<'id> MSTraceSegment<'id> {
 
     /// Returns the number of (unpacked) data samples.
     pub fn num_samples(&self) -> c_long {
-        self.ptr().numsamples
+        self.ptr().numsamples.try_into().unwrap()
```
Comment (damb) [inline src/trace.rs]: Cast with `as _`.

File: src/trace.rs [hunk 20]
```diff
@@ -390,7 +390,7 @@ impl MSTraceList {
             check(raw::mstl3_readbuffer(
                 (&mut rv.get_raw_mut()) as *mut *mut _,
                 buf.as_ptr(),
-                buf.len() as c_ulong,
+                (buf.len() as c_ulong).into(),
```
Comment (damb) [inline src/trace.rs]: See above. Casting twice is not required.

File: src/trace.rs [hunk 21]
```diff
@@ -430,7 +430,7 @@ impl MSTraceList {
                 rec.into_raw(),
                 ptr::null_mut(),
                 0,
-                autoheal as c_char,
+                (autoheal as c_char).try_into().unwrap(),
```
Comment (damb) [inline src/trace.rs]: See above. Casting twice not required.

File: src/trace.rs [hunk 22]
```diff
@@ -521,14 +521,20 @@ impl fmt::Display for TraceListDisplay<'_> {
             };
             for tseg in tid.iter() {
                 let start_time = unsafe { (*tseg.inner).starttime };
-                let start_time_str =
-                    util::nstime_to_string(start_time, self.time_format, MSSubSeconds::NanoMicro)
-                        .map_err(|_| fmt::Error)?;
+                let start_time_str = util::nstime_to_string(
+                    start_time.try_into().unwrap(),
```
Comment (damb) [inline src/trace.rs]: Cast with `as _`.

File: src/trace.rs [hunk 23]
```diff
@@ -521,14 +521,20 @@ impl fmt::Display for TraceListDisplay<'_> {
...
+                    MSSubSeconds::NanoMicro,
+                )
+                .map_err(|_| fmt::Error)?;
 
                 let end_time = unsafe { (*tseg.inner).endtime };
-                let end_time_str =
-                    util::nstime_to_string(end_time, self.time_format, MSSubSeconds::NanoMicro)
-                        .map_err(|_| fmt::Error)?;
+                let end_time_str = util::nstime_to_string(
+                    end_time.try_into().unwrap(),
```
Comment (damb) [inline src/trace.rs]: Cast with `as _`.

File: src/record.rs [hunk 24]
```diff
@@ -180,7 +180,7 @@ impl MSRecord {
             let buf = &*(buf as *const [_] as *const [c_char]);
             check(raw::msr3_parse(
                 buf.as_ptr(),
-                buf.len() as c_ulong,
+                (buf.len() as c_ulong).into(),
```
Comment (damb) [inline src/record.rs]: See above. Casting twice not required.

File: src/pack.rs [hunk 25]
```diff
@@ -68,15 +68,15 @@ where
         extra_ptr = cloned.into_raw();
     }
 
-    let mut cnt_samples: c_long = 0;
-    let cnt_samples_ptr = &mut cnt_samples as *mut _;
+    let cnt_samples: c_long = 0;
```
Comment (damb) [inline src/pack.rs]: This is dangerous and causes a test failure on my local machine. 

`raw::msr3_pack()` is expecting a pointer to a mutable type for returning the number of packed samples.

```rust
    let mut cnt_samples: c_long = 0;
    let cnt_samples_ptr = (&mut cnt_samples as &mut _) as *mut _;
```

is the way to go.

**Review by damb — CHANGES_REQUESTED** [review]
Thanks a lot.

Could you fix the requested changes, please? Also, could you have a look at the examples in the examples directory since they might require additional changes?

In addition, do you have experience with ARM based test runners for GitHub actions? It would be nice to have tests being executed on ARM, too.

File: src/pack.rs (hunk 25 above)
Comment (BIBIN-EUGINE) [reply src/pack.rs]: > ```rust
> (&mut cnt_samples as &mut _) as *mut _;
> ```

I am getting a CC error for this conversion, so I recommend to use the below mentioned way
```
    let cnt_samples: c_long = 0;
    let cnt_samples_ptr = (&mut cnt_samples.into()) as *mut _;

```
**Error**
```
error[E0606]: casting `&mut i32` as `*mut i64` is invalid
   --> src/pack.rs:325:27
    |
325 |     let cnt_samples_ptr = (&mut cnt_samples as &mut _) as *mut _;

```

Comment (damb) [reply src/pack.rs]: The suggested solution is not correct and results in a test failing on my machine (i.e. `x86_64`). `cnt_samples` must be mutable. The actual problem is that on your architecture `c_long` is defined as `i32` while on my side it is `i64` (see: https://doc.rust-lang.org/std/os/raw/type.c_long.html). Does

```rust
let mut cnt_samples: i64 = 0;
let cnt_samples_ptr: *mut i64 = &mut cnt_samples;
```

solve the issue on your side?

EDIT: Thanks for pasting the compiler error :+1:.

Comment (BIBIN-EUGINE) [reply src/pack.rs]: > The suggested solution is not correct and results in a test failing on my machine (i.e. `x86_64`). `cnt_samples` must be mutable. The actual problem is that on your architecture `c_long` is defined as `i32` while on my side it is `i64` (see: https://doc.rust-lang.org/std/os/raw/type.c_long.html). Does
> 
> ```rust
> let mut cnt_samples: i64 = 0;
> let cnt_samples_ptr: *mut i64 = &mut cnt_samples;
> ```
> 
> solve the issue on your side?
> 
> EDIT: Thanks for pasting the compiler error 👍.

Thanks @damb it works.

Comment (damb) [reply src/pack.rs]: Perfect. Thanks.

**Review by damb — APPROVED** [review]

**Comment by damb** [comment]
Thank you again. It would be nice if you still could check whether the examples need a fix. In case of errors a PR is very welcome.

**Comment by BIBIN-EUGINE** [comment]
> Thank you again. It would be nice if you still could check whether the examples need a fix. In case of errors a PR is very welcome.

I have  verified all the examples works as expected.

**Comment by BIBIN-EUGINE** [comment]
> Thanks a lot.
> 
> Could you fix the requested changes, please? Also, could you have a look at the examples in the examples directory since they might require additional changes?
> 
> In addition, do you have experience with ARM based test runners for GitHub actions? It would be nice to have tests being executed on ARM, too.

I haven't explored GitHub actions yet, If you already have experience with this then I am happy for you to pursue.
In addition, I am also seeing some other issues with this crate...will post more about it soon as a separate issue.
